server:
  port: 9090

spring:
  application:
    name: dubbo-provider-application

dubbo:
  # 服务信息
  application:
    name: ${spring.application.name}
  # 注册中心地址
  registry:
    address: zookeeper://192.168.2.235:2181
  # 服务提供者的协议
  protocol:
    name: rest
    port: 8080
    server: tomcat
  # 扫描 Dubbo 相关的注解
  scan:
    base-packages: com.clay.dubbo.provider
