server:
  port: 9090

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: provider-service-v1
          uri: http://127.0.0.1:9091/v1/
          predicates:
            - Path=/test
            - Weight=group, 95
        - id: provider-service-v2
          uri: http://127.0.0.1:9091/v2/
          predicates:
            - Path=/test
            - Weight=group, 5

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false