server:
  port: 9001

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: provider-service-1
          uri: lb://provider-service-1
          predicates:
            - Path=/provider1/**
          filters:
            - GwSwaggerHeaderFilter
            - StripPrefix=1
        - id: provider-service-2
          uri: lb://provider-service-2
          predicates:
            - Path=/provider2/**
          filters:
            - GwSwaggerHeaderFilter
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9000/eureka
  instance:
    instance-id: gateway-server-${server.port}
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false