server:
  port: 8087

spring:
  application:
    name: seata-account-service

  # 注册中心
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.56.112:8848

  # 数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.56.112:3306/seata_account?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: seata
    password: seata

  # Druid 连接池
  druid:
    initial-size: 5
    min-idle: 5
    max-active: 20
    max-wait: 60000
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    validation-query: SELECT 1
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    pool-prepared-statements: true
    max-pool-prepared-statement-per-connection-size: 20
    filters: stat,wall,log4j
    connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

# MyBatis
mybatis:
  mapper-locations: classpath*:mybatis/mapper/*.xml
  type-aliases-package: com.clay.entities
  configuration:
    map-underscore-to-camel-case: true

# Seata
seata:
  # 指定从 Nacos 注册中心获取 Seata Server（TC）的地址
  registry:
    type: nacos
    nacos:
      application: seata-server # Seata Server（TC）的服务名称
      server-addr: 192.168.56.112:8848
      namespace:
      group: SEATA_GROUP
      cluster: default
  # 指定从 Nacos 配置中心获取 Seata Client 的配置信息
  config:
    type: nacos
    nacos:
      server-addr: 192.168.56.112:8848
      namespace:
      group: SEATA_GROUP
      data-id: seata-client.properties
      username:
      password:
  tx-service-group: default_tx_group # 事务组，由它获得 Seata Server（TC）服务的集群名称
  service:
    vgroup-mapping:
      default_tx_group: default # 事务组与 Seata Server（TC）服务集群的映射关系
  data-source-proxy-mode: AT
  application-id: ${spring.application.name}

# 日志
logging:
  level:
    io:
      seata: info
