server:
  port: 9090

spring:
  application: dubbo-provider-application

dubbo:
  application:
    name: ${spring.application}
  registry:
    address: zookeeper://192.168.56.112:2181
  protocol:
    name: dubbo
    port: 20880
