server:
  port: 9003

spring:
  application:
    name: provider-service-2

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9000/eureka
  instance:
    instance-id: provider-service-2-${server.port}
    prefer-ip-address: true