server:
  port: 8021

spring:
  application:
    name: cloud-consumer-feign-order-service
  # 日期序列化格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cloud:
    # Consul
    consul:
      host: 192.168.56.112
      port: 8500
      discovery:
        prefer-ip-address: true  # 优先使用服务IP进行注册
        service-name: ${spring.application.name}
        heartbeat:
          enabled: true
