server:
  port: 9095

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: hystrix_route
          predicates:
            - Path=/test/hystrix
          filters:
            - name: Hystrix                         # Hystrix Filter 的名称
              args:                                 # Hystrix 配置参数
                name: fallbackcmd                   # HystrixCommand 的名字
                fallbackUri: forward:/fallback      # fallback 对应的 uri
          uri: http://127.0.0.1:8080/hystrix?isSleep=false

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000         # Hystrix 的 fallbackcmd 的超时时间

management:
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG