server:
  port: 8005

spring:
  application:
    name: gateway-service
  cloud:
    # Nacos
    nacos:
      discovery:
        server-addr: 192.168.56.112:8848
    # Gateway
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: consumer_route
          uri: lb://consumer-service
          predicates:
            - Path=/consumer/**
        - id: baidu_route
          uri: https://www.baidu.com
          predicates:
            - Path=/baidu/**
          filters:
            - RewritePath=/baidu/(?<segment>.*), /$\{segment}
