server:
  port: 8093

spring:
  application:
    name: turbine-service

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8090/eureka
  instance:
    prefer-ip-address: true

turbine:
  aggregator:
    clusterConfig: default    #指定聚合哪些集群，多个使用","分割，默认为default。可使用http://.../turbine.stream?cluster={clusterConfig之一}访问
  appConfig: provider-dept,provider-user    #配置Eureka中的serviceId列表，表明监控哪些服务
  clusterNameExpression: "'default'"
  # 1.当clusterNameExpression: default时，turbine.aggregator.clusterConfig可以不写，因为默认就是default
  # 2.当clusterNameExpression指定集群名称，默认表达式appName；此时：turbine.aggregator.clusterConfig需要配置想要监控的应用名称
  # 3.当clusterNameExpression: metadata['cluster']时，假设想要监控的应用配置了eureka.instance.metadata-map.cluster: ABC，则需要配置，同时turbine.aggregator.clusterConfig: ABC
