server:
  port: 9004

spring:
  application:
    name: consul-consumer-discovery-client
  cloud:
    consul:
      host: 127.0.0.1    # consul 启动地址
      port: 8500         # consul 启动端口
      discovery:
        server-list-query-tags:
          consul-provider: tag1     # 在调用 consul-provider 服务时，使用 tag1 对应的服务实例