server:
  port: 9001

spring:
  application:
    name: consul-provider
  cloud:
    consul:
      host: 127.0.0.1    # consul 启动地址
      port: 8500         # consul 启动端口
      discovery:
        tags: tag1