server:
  port: 9090

spring:
  application:
    name: dubbo-provider-application

dubbo:
  # 服务信息
  application:
    name: ${spring.application.name}
  # 注册中心地址（直连）
  registry:
    address: N/A
  # 服务提供者的协议
  protocol:
    name: rmi
    port: 1099
  # 扫描 Dubbo 相关的注解
  scan:
    base-packages: com.clay.dubbo.provider
