server:
  port: 9090

spring:
  application:
    name: dubbo-provider-application

dubbo:
  # 服务信息
  application:
    name: ${spring.application.name}
  # 注册中心地址
  registry:
    address: nacos://192.168.2.235:8848
  # 服务提供者的协议
  protocol:
    name: dubbo
    port: 20880
  # 扫描 Dubbo 相关的注解
  scan:
    base-packages: com.clay.dubbo.provider
