server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  # 日期序列化格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # 数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.56.112:3306/spring_cloud?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: cloud
    password: 123456
  cloud:
    # Consul
    consul:
      host: 192.168.56.112
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        heartbeat:
          enabled: true

# MyBatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.turing.cloud.entities
  configuration:
    map-underscore-to-camel-case: true
