server:
  port: 8001

spring:
  # 激活不同的配置环境
  profiles:
    active: dev
  # 日期序列化格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # 数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.56.112:3306/spring_cloud_2024?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: cloud
    password: 123456

# MyBatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.turing.cloud.entities
  configuration:
    map-underscore-to-camel-case: true

management:
  # Zipkin
  zipkin:
    tracing:
      endpoint: http://192.168.56.112:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0  # 采样率默认为 0.1（这里的 0.1 表示 10 次只能有一次被记录下来)，值越大收集越及时
