server:
  port: 9002

spring:
  application:
    name: provider-service-1

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9000/eureka
  instance:
    instance-id: provider-service-1-${server.port}
    prefer-ip-address: true