server:
  port: 8082
  servlet:
    context-path: /consumer

spring:
  application:
    name: sentinel-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: 4bfcbae8-8c37-417d-89e4-d5134e23eb18
        cluster-name: DEFAULT
    sentinel:
      transport:
        dashboard: 127.0.0.1:9000

feign:
  sentinel:
    enabled: true