server:
  port: 8080

spring:
  application:
    name: rabbit-application
  rabbitmq:
    host: 192.168.2.127
    port: 5672
    password: admin
    username: admin
    virtual-host: /
    # 启用发布确认机制
    publisher-confirm-type: correlated
    # 启用消息退回机制
    publisher-returns: true
