server:
  port: 8011

spring:
  application:
    name: cloud-order-service
  # 日期序列化格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cloud:
    # Consul
    consul:
      host: 192.168.56.112
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        heartbeat:
          enabled: true
