spring:
  data:
    redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      password: marketHdege
      lettuce:
        pool:
          max-active: 8
          max-wait: -1ms
          max-idle: 8
          min-idle: 0
