server:
  port: 8003

spring:
  application:
    name: consumer-service
  cloud:
    # Consul
    consul:
      host: 192.168.56.112
      port: 8500
      # 注册中心
      discovery:
        service-name: ${spring.application.name}
        heartbeat:
          enabled: true
    # OpenFeign
    openfeign:
      # 开启断路器和分组激活
      circuitbreaker:
        enabled: true
        group:
          enabled: true  # 没有开启分组则永远不用分组的配置。精确优先、分组次之（开了分组）、默认最后

# Resilience4j
resilience4j:
  timelimiter:
    configs:
      default:
        timeout-duration: 20s  # 神坑的位置，timelimiter 默认限制请求处理耗时为 1s，超过 1s 就会认为请求超时，如果配置了降级，就会走降级逻辑
  # 隔离（舱壁）
  bulkhead:
    configs:
      # 隔离（舱壁）的默认配置
      default:
        maxConcurrentCalls: 2  # 隔离允许并发执行的最大线程数
        maxWaitDuration: 1s  # 当达到最大并发执行数量时，新的线程执行时将会被阻塞，这个属性表示线程最长的阻塞等待时间；如果等待超时，直接走 Fallback 兜底处理
    instances:
      # 指定特定的服务使用哪个隔离（舱壁）配置
      provider-service:
        baseConfig: default
