server:
  port: 9002

spring:
  application:
    name: admin-client
  boot:
    admin:
      client:
        url: http://127.0.0.1:9001    #Spring Boot Admin Server 的地址
        instance:
          prefer-ip: true             #将IP注册到Admin Server上，若不配置默认使用机器的主机名

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

logging:
  file: /tmp/admin/client.log