server:
  port: 9001

spring:
  application:
    name: admin-server
  security:
    user:
      name: "admin"
      password: "admin"

eureka:
  client:
    registryFetchIntervalSeconds: 5
    service-url:
      defaultZone: http://127.0.0.1:9003/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    instance-id: ${spring.application.name}-${server.port}         #自定义服务名称
    prefer-ip-address: true                                        #将IP注册到Eureka Server上，若不配置默认使用机器的主机名
    metadata-map:                                                  #指定Spring Security的用户名和密码
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS