server:
  port: 9003

spring:
  application:
    name: consumer-service

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9000/eureka
  instance:
    instance-id: consumer-service-${server.port}
    prefer-ip-address: true